import { CreateProvider } from "@/context/lessonContext";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { CartProvider } from "./context/cartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Context API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <CartProvider>
        <CreateProvider>
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </CreateProvider>
      </CartProvider>
    </html>
  );
}
